#ifndef CHECKHEADER_SLIB_SFILE_DEFINITION
#define CHECKHEADER_SLIB_SFILE_DEFINITION

#include "../../slib/core/definition.h"

#define SLIB_SFILE_NAMESPACE_START		SLIB_NAMESPACE_START
#define SLIB_SFILE_NAMESPACE_END		SLIB_NAMESPACE_END

#endif
