#ifndef CHECKHEADER_SLIB_MAP_DATA_CONFIG
#define CHECKHEADER_SLIB_MAP_DATA_CONFIG

#define SLIB_MAP_PICTURE_TILE_EXT _SLT(".jpg")
#define SLIB_MAP_DEM_TILE_EXT _SLT(".bil")
#define SLIB_MAP_GIS_LINE_TILE_EXT _SLT(".lin")
#define SLIB_MAP_GIS_POI_TILE_EXT _SLT(".poi")
#define SLIB_MAP_BUILDING_TILE_EXT _SLT(".dat")

#define SLIB_MAP_PICTURE_PACKAGE_DIMENSION 128
#define SLIB_MAP_DEM_PACKAGE_DIMENSION 256
#define SLIB_MAP_GIS_PACKAGE_DIMENSION 256
#define SLIB_MAP_BUILDING_PACKAGE_DIMENSION 32

#define SLIB_MAP_PICTURE_TILE_TYPE _SLT("picture")
#define SLIB_MAP_DEM_TILE_TYPE _SLT("dem")
#define SLIB_MAP_GIS_LINE_TILE_TYPE _SLT("gis/line")
#define SLIB_MAP_GIS_POI_TILE_TYPE _SLT("gis/poi")
#define SLIB_MAP_BUILDING_TILE_TYPE _SLT("real3d/facility_build")
#define SLIB_MAP_BUILDING_WORLD_TILE_TYPE _SLT("real3d/facility_build_world")
#define SLIB_MAP_BRIDGE_TILE_TYPE _SLT("real3d/facility_bridge")

#endif
