#ifndef CHECKHEADER_SLIB_MAP_DEFINITION
#define CHECKHEADER_SLIB_MAP_DEFINITION

#include "../../slib/core/definition.h"

#define SLIB_MAP_NAMESPACE_START		SLIB_NAMESPACE_START
#define SLIB_MAP_NAMESPACE_END			SLIB_NAMESPACE_END

#endif
