#ifndef CHECKHEADER_SLIB_MAP_TILE_CONFIG
#define CHECKHEADER_SLIB_MAP_TILE_CONFIG

#define SLIB_MAP_TILE_LIFE_MILLISECONDS 10000

#define SLIB_MAP_MAX_PICTURE_TILES_COUNT 300

#define SLIB_MAP_MAX_DEM_TILES_COUNT 2000

#define SLIB_MAP_MAX_BUILDING_TILES_COUNT 100
#define SLIB_MAP_MAX_BUILDINGS_COUNT 1000
#define SLIB_MAP_MAX_DETAILED_BUILDINGS_COUNT 50

#define SLIB_MAP_MAX_GIS_LINE_TILES_COUNT 200

#define SLIB_MAP_MAX_GIS_POI_TILES_COUNT 200

#define SLIB_MAP_MAX_RENDER_TILES_COUNT 100

#endif
