#ifndef CHECKHEADER_SLIB_MAP_DEFINITION
#define CHECKHEADER_SLIB_MAP_DEFINITION

#include <slib/core/definition.h>

#define SLIB_MAP_NAMESPACE_BEGIN		SLIB_NAMESPACE_BEGIN
#define SLIB_MAP_NAMESPACE_END			SLIB_NAMESPACE_END

#define SLIB_SMAP_MAX_LAYERS_COUNT 4

#endif
