#ifndef CHECKHEADER_SLIB_SNET_DEFINITION
#define CHECKHEADER_SLIB_SNET_DEFINITION

#include <slib/core/definition.h>

#define SLIB_SNET_NAMESPACE_BEGIN		SLIB_NAMESPACE_BEGIN
#define SLIB_SNET_NAMESPACE_END			SLIB_NAMESPACE_END

#endif
